import React from "react";

export const metadata = {
  title: "Edit Post - Neonthoughts",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return <>{children}</>;
}
